# Generated by Django 5.2.17 on 2026-10-01 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('peso_kg', models.FloatField()),
                ('medio', models.CharField(blank=True, max_length=30)),
                ('motivo_medio', models.CharField(blank=True, max_length=200)),
                ('eta_minutos', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado')], default='CREADO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confirmado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cobro', to='entregas.pedido')),
            ],
        ),
    ]
